# Generated by Django 4.2.18 on 2025-02-09 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_booking', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SpecialOpeningHours',
        ),
    ]
