# Generated by Django 4.2.18 on 2025-02-09 19:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_booking', '0002_delete_specialopeninghours'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(verbose_name='Nap')),
                ('is_even_week', models.BooleanField(verbose_name='Páros hét?')),
                ('start_time', models.TimeField(verbose_name='Nyitás')),
                ('end_time', models.TimeField(verbose_name='Zárás')),
                ('status', models.CharField(choices=[('pending', 'Függőben'), ('accepted', 'Elfogadva'), ('cancelled', 'Lemondva')], default='pending', max_length=10)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Foglaló')),
            ],
        ),
    ]
