# Generated by Django 4.2.18 on 2025-02-09 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_booking', '0003_booking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='day_of_week',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='is_even_week',
        ),
        migrations.AddField(
            model_name='booking',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='Dátum'),
        ),
    ]
