# Generated by Django 4.2.18 on 2025-02-11 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_booking', '0005_remove_booking_end_time_booking_billing_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='billing_city',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='booking',
            name='billing_tax_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='billing_zip',
            field=models.CharField(default=0, max_length=10),
        ),
        migrations.AddField(
            model_name='booking',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='newsletter',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='booking',
            name='billing_address',
            field=models.TextField(default=''),
        ),
    ]
