# Generated by Django 4.2.18 on 2025-02-11 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_booking', '0006_booking_billing_city_booking_billing_tax_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='customer_phone',
            field=models.CharField(default='', max_length=20),
        ),
    ]
