# Generated by Django 4.2.18 on 2025-02-11 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_booking', '0007_booking_customer_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='service_type',
            field=models.TextField(default=''),
        ),
    ]
