# Generated by Django 4.2.18 on 2025-02-12 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_booking', '0009_remove_booking_service_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingsettings',
            name='booking_puffer',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=3, verbose_name='puffer idő (percekben)'),
            preserve_default=False,
        ),
    ]
