# Generated by Django 4.2.18 on 2025-02-13 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_booking', '0011_alter_bookingsettings_booking_puffer'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='admin_token',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
    ]
