# Generated by Django 4.2.18 on 2025-02-18 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_booking', '0013_alter_booking_booked_service_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='admin_token',
            field=models.CharField(blank=True, editable=False, max_length=64, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='billing_address',
            field=models.TextField(default='', verbose_name='Számlázási cím: utca, házszám'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='billing_city',
            field=models.CharField(default='', max_length=255, verbose_name='Számlázási cím: város'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='billing_tax_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Adószám'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='billing_zip',
            field=models.CharField(default=0, max_length=10, verbose_name='Irányítószám'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='booked_service_type',
            field=models.CharField(default='', max_length=30, verbose_name='Masszázs fajtája'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='customer_phone',
            field=models.CharField(default='', max_length=20, verbose_name='Vevő telefonszáma'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='newsletter',
            field=models.BooleanField(default=False, verbose_name='Hírlevél feliratkozás'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'Függőben'), ('accepted', 'Elfogadva'), ('cancelled', 'Lemondva')], default='pending', max_length=10, verbose_name='Foglalás státusza'),
        ),
    ]
