# Generated by Django 4.2.18 on 2025-02-18 22:22

from django.db import migrations, models
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app_booking', '0014_alter_booking_admin_token_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('pending', 'Függőben lévő foglalás'), ('accepted', 'Elfogadott foglalás'), ('auto_rejected', 'Automatikusan elutasított foglalás')], max_length=20, unique=True)),
                ('content', django_quill.fields.QuillField()),
            ],
        ),
    ]
