# Generated by Django 4.2.18 on 2025-02-19 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_booking', '0015_emailtemplate'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emailtemplate',
            options={'verbose_name': 'Email sablon', 'verbose_name_plural': 'Email sablonok'},
        ),
    ]
