# Generated by Django 4.2.18 on 2025-02-19 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_booking', '0016_alter_emailtemplate_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingsettings',
            name='contraindications_pdf',
            field=models.FileField(blank=True, null=True, upload_to='pdfs/', verbose_name='Ellenjavallatok PDF'),
        ),
        migrations.AddField(
            model_name='bookingsettings',
            name='privacy_policy_pdf',
            field=models.FileField(blank=True, null=True, upload_to='pdfs/', verbose_name='Adatvédelmi irányelvek PDF'),
        ),
        migrations.AddField(
            model_name='bookingsettings',
            name='terms_conditions_pdf',
            field=models.FileField(blank=True, null=True, upload_to='pdfs/', verbose_name='Felhasználási feltételek PDF'),
        ),
    ]
