# Generated by Django 4.2.18 on 2025-02-24 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_booking', '0017_bookingsettings_contraindications_pdf_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='newsletter',
        ),
        migrations.AlterField(
            model_name='emailtemplate',
            name='type',
            field=models.CharField(choices=[('pending', 'Függőben lévő foglalás'), ('accepted', 'Elfogadott foglalás'), ('auto_rejected', 'Elutasított foglalás')], max_length=20, unique=True),
        ),
    ]
