# Generated by Django 4.2.18 on 2025-02-24 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_booking', '0018_remove_booking_newsletter_alter_emailtemplate_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='billing_email',
            field=models.EmailField(blank=True, default='', max_length=254, null=True, verbose_name='Számlázási email'),
        ),
    ]
