# Generated by Django 4.2.18 on 2025-02-24 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_booking', '0021_remove_booking_billing_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailtemplate',
            name='type',
            field=models.CharField(choices=[('pending', 'Függőben lévő foglalás'), ('accepted', 'Elfogadott foglalás'), ('cancelled', 'Elutasított foglalás'), ('post_cancelled', 'Utólag elutasított foglalás')], max_length=30, unique=True),
        ),
    ]
