# Generated by Django 4.2.18 on 2025-02-24 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_booking', '0022_alter_emailtemplate_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingsettings',
            name='is_reviews_enabled',
            field=models.BooleanField(default=True, verbose_name='Reviewk megjenítése?'),
        ),
    ]
