# Generated by Django 4.2.18 on 2025-03-17 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_booking', '0024_alter_booking_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'Függőben'), ('accepted', 'Elfogadva'), ('cancelled', 'Lemondva'), ('post_cancelled', 'Utólag Lemondva')], default='pending', max_length=20, verbose_name='Foglalás státusza'),
        ),
        migrations.AlterField(
            model_name='emailtemplate',
            name='type',
            field=models.CharField(choices=[('pending', 'Függőben lévő foglalás'), ('accepted', 'Elfogadott foglalás'), ('cancelled', 'Elutasított foglalás'), ('post_cancelled', 'Utólag elutasított foglalás'), ('reminder', 'Foglalási emlékeztető')], max_length=30, unique=True),
        ),
    ]
