# Generated by Django 4.0.3 on 2025-01-27 19:45

import app_bettirelax.models
from django.db import migrations, models
import django.db.models.deletion
import django_quill.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_image', models.ImageField(upload_to='app_brandon_photography/img/photos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.CharField(default='Nagy Ádám', max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('extract', models.CharField(max_length=200)),
                ('content', django_quill.fields.QuillField()),
                ('slug', models.SlugField(blank=True, max_length=200, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=255, unique=True, verbose_name='szolgáltatás neve')),
                ('service_main_img', models.ImageField(upload_to='services/main_images/', verbose_name='főkép')),
                ('service_secondary_img', models.ImageField(blank=True, null=True, upload_to='services/secondary_images/', verbose_name='másodlagos kép')),
                ('service_main_description', models.TextField(verbose_name='elsődleges leírás')),
                ('service_secondary_description', models.TextField(blank=True, null=True, verbose_name='másodlagos leírás')),
            ],
            bases=(app_bettirelax.models.ImageHandlerMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ServicePrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_description', models.CharField(max_length=255, verbose_name='időtartam')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='ár')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='app_bettirelax.service')),
            ],
        ),
    ]
