# Generated by Django 4.0.3 on 2025-01-27 19:53

from django.db import migrations
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app_bettirelax', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='service_main_description',
            field=django_quill.fields.QuillField(verbose_name='elsődleges leírás'),
        ),
        migrations.AlterField(
            model_name='service',
            name='service_secondary_description',
            field=django_quill.fields.QuillField(blank=True, null=True, verbose_name='másodlagos leírás'),
        ),
    ]
