# Generated by Django 4.0.3 on 2025-01-29 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_bettirelax', '0002_alter_service_service_main_description_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogpost',
            options={'verbose_name': 'Blogposzt', 'verbose_name_plural': 'Blogposztok'},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'verbose_name': 'Szolgáltatás', 'verbose_name_plural': 'Szolgáltatások'},
        ),
        migrations.AlterModelOptions(
            name='serviceprice',
            options={'verbose_name': 'Szolgáltatás ár', 'verbose_name_plural': 'Szolgáltatás árak'},
        ),
        migrations.RemoveField(
            model_name='serviceprice',
            name='price_description',
        ),
        migrations.AddField(
            model_name='serviceprice',
            name='duration_minutes',
            field=models.PositiveIntegerField(default=0, verbose_name='időtartam percekben'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='serviceprice',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='serviceprice',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='árak', to='app_bettirelax.service'),
        ),
    ]
