# Generated by Django 4.0.3 on 2025-01-29 09:41

from django.db import migrations, models
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app_bettirelax', '0003_alter_blogpost_options_alter_service_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutMe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='app_bettirelax/img/photos/', verbose_name='bemutatkozó kép')),
                ('aboutme', django_quill.fields.QuillField(verbose_name='bemutatkozó szöveg')),
            ],
            options={
                'verbose_name': 'Rólam',
                'verbose_name_plural': 'Rólam',
            },
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='main_image',
            field=models.ImageField(upload_to='app_bettirelax/img/photos/'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='user',
            field=models.CharField(default='Betti', max_length=200),
        ),
        migrations.AlterField(
            model_name='service',
            name='service_main_img',
            field=models.ImageField(upload_to='app_bettirelax/img/photos/', verbose_name='főkép'),
        ),
        migrations.AlterField(
            model_name='service',
            name='service_secondary_img',
            field=models.ImageField(blank=True, null=True, upload_to='app_bettirelax/img/photos/', verbose_name='másodlagos kép'),
        ),
        migrations.AlterField(
            model_name='serviceprice',
            name='duration_minutes',
            field=models.PositiveIntegerField(verbose_name='időtartam (perc)'),
        ),
        migrations.AlterField(
            model_name='serviceprice',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='ár (Ft)'),
        ),
    ]
