# Generated by Django 4.0.3 on 2025-01-29 09:54

import app_bettirelax.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_bettirelax', '0004_aboutme_alter_blogpost_main_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(verbose_name='kérdés')),
                ('answer', models.TextField(verbose_name='válasz')),
            ],
            options={
                'verbose_name': 'Gyakori kérdések',
                'verbose_name_plural': 'Gyakori kérdések',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='név')),
                ('stars', models.PositiveSmallIntegerField(verbose_name='csillagok száma')),
                ('description', models.TextField(verbose_name='értékelés szövege')),
                ('photo', models.ImageField(default='app_brandon_photography/img/photos/default.jpg', upload_to='app_bettirelax/img/photos/')),
                ('photo_tumb', models.ImageField(default='app_brandon_photography/img/photos/default.jpg', editable=False, upload_to='app_bettirelax/img/thumbs/')),
            ],
            options={
                'verbose_name': 'Értékelés',
                'verbose_name_plural': 'Értékelések',
            },
            bases=(app_bettirelax.models.ImageHandlerMixin, models.Model),
        ),
    ]
