# Generated by Django 4.0.3 on 2025-01-29 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_bettirelax', '0005_faq_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='service_main_img_photo_tumb',
            field=models.ImageField(blank=True, editable=False, null=True, upload_to='app_menhely/img/thumbs/'),
        ),
        migrations.AddField(
            model_name='service',
            name='service_secondary_img_photo_tumb',
            field=models.ImageField(blank=True, editable=False, null=True, upload_to='app_menhely/img/thumbs/'),
        ),
    ]
