# Generated by Django 4.0.3 on 2025-01-29 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_bettirelax', '0006_service_service_main_img_photo_tumb_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='service_main_img_photo_tumb',
        ),
        migrations.RemoveField(
            model_name='service',
            name='service_secondary_img_photo_tumb',
        ),
        migrations.AddField(
            model_name='service',
            name='service_main_img_photo_thumb',
            field=models.ImageField(blank=True, editable=False, null=True, upload_to='app_bettirelax/img/thumbs/'),
        ),
        migrations.AddField(
            model_name='service',
            name='service_secondary_img_thumb',
            field=models.ImageField(blank=True, editable=False, null=True, upload_to='app_bettirelax/img/thumbs/'),
        ),
    ]
