# Generated by Django 4.0.3 on 2025-01-29 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_bettirelax', '0007_remove_service_service_main_img_photo_tumb_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='service_main_img_photo_thumb',
            new_name='service_main_img_thumb',
        ),
    ]
