# Generated by Django 4.0.3 on 2025-01-30 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_bettirelax', '0010_contact_alter_blogpost_slug_alter_service_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='adress_link',
            field=models.TextField(default='', max_length=500, verbose_name='térkép link'),
        ),
    ]
