# Generated by Django 4.0.3 on 2025-01-30 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_bettirelax', '0011_alter_contact_adress_link'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='email_adress',
            new_name='email_address',
        ),
    ]
