# Generated by Django 4.0.3 on 2025-01-30 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_bettirelax', '0012_rename_email_adress_contact_email_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='adress',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='adress_link',
            new_name='address_link',
        ),
    ]
