# Generated by Django 4.0.3 on 2025-01-30 21:34

from django.db import migrations
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app_bettirelax', '0014_contact_facebook_messenger'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='contact_text',
            field=django_quill.fields.QuillField(default='', verbose_name='kapcsolat szöveg'),
        ),
    ]
