# Generated by Django 4.0.3 on 2025-01-31 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_bettirelax', '0016_alter_serviceprice_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutme',
            name='photo_thumb',
            field=models.ImageField(blank=True, editable=False, null=True, upload_to='app_bettirelax/img/thumbs/'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='main_image_thumb',
            field=models.ImageField(blank=True, editable=False, null=True, upload_to='app_bettirelax/img/thumbs/'),
        ),
    ]
