# Generated by Django 4.2.18 on 2025-02-06 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_bettirelax', '0017_aboutme_photo_thumb_blogpost_main_image_thumb'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='address',
        ),
        migrations.AddField(
            model_name='contact',
            name='address_city',
            field=models.CharField(default='', max_length=50, verbose_name='cím: város'),
        ),
        migrations.AddField(
            model_name='contact',
            name='address_country',
            field=models.CharField(default='', max_length=50, verbose_name='cím: ország'),
        ),
        migrations.AddField(
            model_name='contact',
            name='address_county',
            field=models.CharField(default='', max_length=50, verbose_name='cím: megye'),
        ),
        migrations.AddField(
            model_name='contact',
            name='address_postal',
            field=models.CharField(default='', max_length=50, verbose_name='cím: irányítószám'),
        ),
        migrations.AddField(
            model_name='contact',
            name='address_street',
            field=models.CharField(default='', max_length=50, verbose_name='cím: utca, házszám'),
        ),
    ]
