# Generated by Django 4.2.18 on 2025-02-09 23:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_bettirelax', '0021_bookingsettings_specialopeninghours_openinghours'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BookingSettings',
        ),
        migrations.DeleteModel(
            name='OpeningHours',
        ),
        migrations.DeleteModel(
            name='SpecialOpeningHours',
        ),
    ]
