# Generated by Django 4.2.18 on 2025-02-24 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_bettirelax', '0022_delete_bookingsettings_delete_openinghours_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='photo',
            field=models.ImageField(upload_to='app_bettirelax/img/photos/'),
        ),
        migrations.AlterField(
            model_name='review',
            name='photo_tumb',
            field=models.ImageField(editable=False, upload_to='app_bettirelax/img/thumbs/'),
        ),
    ]
