# Generated by Django 4.2.18 on 2025-02-24 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_bettirelax', '0023_alter_review_photo_alter_review_photo_tumb'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='photo_tumb',
            new_name='photo_thumb',
        ),
    ]
