# Generated by Django 4.2.18 on 2025-02-24 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_bettirelax', '0024_rename_photo_tumb_review_photo_thumb'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='is_reviews_enabled',
            field=models.BooleanField(default=True, verbose_name='Reviewk megjenítése?'),
        ),
    ]
