# Generated by Django 4.2.18 on 2025-02-24 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_bettirelax', '0025_review_is_reviews_enabled'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='is_reviews_enabled',
        ),
    ]
